<Project Sdk="Uno.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net8.0-desktop</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>
    <UnoIconForegroundFile>Assets/Icons/logo.png</UnoIconForegroundFile>
    <UnoSplashScreenFile>Assets/Splash/logo_splash.png</UnoSplashScreenFile>

    <!-- Display name -->
    <ApplicationTitle>Cryptograph Forest</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>ch.silvanbauer.CryptoForestApp</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>Silvan Bauer</ApplicationPublisher>
    <!-- Package Description -->
    <Description>CryptoForestApp powered by Uno Platform.</Description>

    <!--
      UnoFeatures let's you quickly add and manage implicit package references based on the features you want to use.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
        Navigation;
        Hosting;
        MVUX;
        Configuration;
        Localization;
        SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CryptoForestLib\CryptoForestLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Presentation\Pages\HistoryPage.xaml.cs">
      <DependentUpon>HistoryPage.xaml</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Dialogs\MoveContentDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Pages\CryptoForestPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Pages\CryptoForestPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Pages\AddItemPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Pages\AddLevelPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Presentation\Dialogs\DecryptedContentDialog.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
